export const ReasonCode = {
  GROUP_SATISFIED: "GROUP_SATISFIED",
  GROUP_NOT_SATISFIED: "GROUP_NOT_SATISFIED",
  GROUP_UNKNOWN: "GROUP_UNKNOWN",
  PROGRAM_FACT_UNKNOWN: "PROGRAM_FACT_UNKNOWN",
  VERIFIED_COURSE_MATCH: "VERIFIED_COURSE_MATCH",
  REQUIRED_COURSE_ABSENT: "REQUIRED_COURSE_ABSENT",
  COURSE_HISTORY_INCOMPLETE: "COURSE_HISTORY_INCOMPLETE",
  COURSE_MAPPING_UNRESOLVED: "COURSE_MAPPING_UNRESOLVED",
  VERIFIED_TEST_PRESENT: "VERIFIED_TEST_PRESENT",
  REQUIRED_TEST_ABSENT: "REQUIRED_TEST_ABSENT",
  TEST_HISTORY_INCOMPLETE: "TEST_HISTORY_INCOMPLETE",
  SOFT_REQUIREMENT_NON_BLOCKING: "SOFT_REQUIREMENT_NON_BLOCKING",
  EXPLICIT_CONDITION_APPLIES: "EXPLICIT_CONDITION_APPLIES",
} as const;

export type ReasonCode = (typeof ReasonCode)[keyof typeof ReasonCode];
