/* eslint-disable */
/* Generated by scripts/generate-v02-registry.mjs — do not edit by hand. */
export const KNOWLEDGE_STATES = [
  "KNOWN",
  "UNKNOWN",
  "NOT_PUBLICLY_DISCLOSED",
  "NOT_YET_RESEARCHED",
  "NOT_YET_VERIFIED",
  "NOT_APPLICABLE",
  "SOURCE_CONFLICT",
  "STALE",
] as const;
export type KnowledgeStatusV02 = (typeof KNOWLEDGE_STATES)[number];

export const TRUTH_STATES = [
  "SATISFIED",
  "NOT_SATISFIED",
  "UNKNOWN",
] as const;
export type TruthValueV02 = (typeof TRUTH_STATES)[number];

export const PROJECTION_VALUES = [
  "SATISFIED",
  "NOT_SATISFIED",
  "UNKNOWN",
  "ABSENT",
] as const;
export type ProjectionValue = (typeof PROJECTION_VALUES)[number];

export const OUTCOMES = [
  "ELIGIBLE",
  "NOT_ELIGIBLE",
  "UNKNOWN",
  "CONDITIONALLY_ELIGIBLE",
] as const;
export type EligibilityOutcomeV02 = (typeof OUTCOMES)[number];

export const PROJECTIONS = [
  "FULL",
  "ORDINARY_BARRIER",
  "CONDITIONAL_HARD",
  "CONDITIONAL_ONLY",
  "SOFT_EXPLANATION",
] as const;
export type EligibilityProjection = (typeof PROJECTIONS)[number];

export const OPERATORS = [
  "ALL",
  "ANY",
  "AT_LEAST",
] as const;
export type GroupOperatorV02 = (typeof OPERATORS)[number];

export const STRENGTHS = [
  "HARD",
  "SOFT",
] as const;
export type RequirementStrengthV02 = (typeof STRENGTHS)[number];

export const SEMANTICS = [
  "ORDINARY",
  "EXPLICIT_CONDITIONAL",
] as const;
export type RequirementSemanticsV02 = (typeof SEMANTICS)[number];

export const MAPPING_STATUSES = [
  "PROPOSED",
  "VERIFIED",
  "REJECTED",
  "RETIRED",
] as const;
export type MappingStatusV02 = (typeof MAPPING_STATUSES)[number];

export const UNIVERSE_ROLES = [
  "AUTHORITATIVE",
  "LIMITING",
] as const;
export type UniverseRoleV02 = (typeof UNIVERSE_ROLES)[number];

export const SCOPE_KINDS = [
  "GLOBAL_PROFILE",
  "EDUCATION_CONTEXT",
  "UNASSIGNED_CONTEXT",
] as const;
export type ScopeKindV02 = (typeof SCOPE_KINDS)[number];

export const PREDICATE_KINDS = [
  "HAS_COURSE_CONCEPT",
  "HAS_TEST",
] as const;
export type PredicateKindV02 = (typeof PREDICATE_KINDS)[number];

export const LEAF_CLASSES = [
  "ORDINARY_HARD",
  "CONDITIONAL_HARD",
  "SOFT",
] as const;
export type LeafClass = (typeof LEAF_CLASSES)[number];

export const REASON_CODES = [
  "GROUP_SATISFIED",
  "GROUP_NOT_SATISFIED",
  "GROUP_UNKNOWN",
  "GROUP_ABSENT",
  "PROGRAM_FACT_UNKNOWN",
  "VERIFIED_COURSE_MATCH",
  "REQUIRED_COURSE_ABSENT",
  "COURSE_HISTORY_INCOMPLETE",
  "COURSE_MAPPING_UNRESOLVED",
  "VERIFIED_TEST_PRESENT",
  "REQUIRED_TEST_ABSENT",
  "TEST_HISTORY_INCOMPLETE",
  "SOFT_REQUIREMENT_NON_BLOCKING",
  "EXPLICIT_CONDITION_APPLIES",
  "PROPOSED_MAPPING_LIMITING",
  "TAXONOMY_CONCEPT_INACTIVE_AT_PIN",
  "UNASSIGNED_CONTEXT_COMPLETENESS_UNAVAILABLE",
] as const;
export type ReasonCodeV02Name = (typeof REASON_CODES)[number];

export const MISSING_DATA_CODES = [
  "PROGRAM_FACT_NOT_KNOWN",
  "MAPPED_COURSE_NOT_INCLUDED",
  "COURSE_EDUCATION_CONTEXT_MISMATCH",
  "INCOMPLETE_COURSE_OR_MAPPING_COVERAGE",
  "NO_VERIFIED_MAPPING",
  "PROPOSED_MAPPING_LIMITING",
  "INCOMPLETE_TEST_HISTORY",
  "INCOMPLETE_EDUCATION_HISTORY",
  "TAXONOMY_CONCEPT_INACTIVE_AT_PIN",
  "UNASSIGNED_CONTEXT_COMPLETENESS_UNAVAILABLE",
] as const;
export type MissingDataCodeV02 = (typeof MISSING_DATA_CODES)[number];

export const CONTRACT = {
  releaseCode: "phase2-v0.2",
  inputSchemaVersion: "eligibility-v0.2",
  resultSemanticsVersion: "eligibility-v0.2",
  canonicalizationVersion: "eligibility-v0.2-c14n1",
  negativeProofVersion: "eligibility-v0.2-neg1",
} as const;
